name: tests-client-cms

on: 
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client-cms && npm install && npm run test:ci
      
